# Generated by Django 6.0.7 on 2026-07-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ckdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_p', models.FloatField()),
                ('hsc_p', models.FloatField()),
                ('degree_p', models.FloatField()),
                ('etest_p', models.FloatField()),
                ('mba_p', models.FloatField()),
                ('gender_M', models.BooleanField(default=False)),
                ('ssc_b_Others', models.BooleanField(default=False)),
                ('hsc_b_Others', models.BooleanField(default=False)),
                ('hsc_s_Commerce', models.BooleanField(default=False)),
                ('hsc_s_Science', models.BooleanField(default=False)),
                ('degree_t_Others', models.BooleanField(default=False)),
                ('degree_t_Sci_Tech', models.BooleanField(default=False)),
                ('workex_Yes', models.BooleanField(default=False)),
                ('specialisation_Mkt_HR', models.BooleanField(default=False)),
            ],
        ),
    ]
